# Generated by Django 3.2.8 on 2021-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20211007_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('YES', 'Выполнена'), ('PL', 'Запланирована'), ('NOT', 'Отменена')], max_length=50),
        ),
    ]
