# Generated by Django 3.2.8 on 2021-10-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('YES', 'Выполнено'), ('PL', 'Запланировано'), ('NOT', 'Отменено')], max_length=50),
        ),
    ]
